language: python
python:
  - '2.7'
install: pip install -r requirements.txt
script: chalice deploy
notifications:
  slack:
    on_success: always
    on_failure: change
    template:
      - "%{build_url}"
      - "%{commit_message}"
      - 'Change view: %{compare_url}'
